[package]
name = "better-install"
version = "0.1.0"
authors = ["Zoe Juozapaitis <jragonmiris@gmail.com>"]

[dependencies]
clap = { version="~2.30.0", features=["yaml"]}
error-chain = "0.11"

[target.'cfg(not(windows))'.dependencies]
git2 = "0.6"